### ISSUE TITLE
ボタンの色が変わらない

### ISSUE THREAD

**Issue by kazubetsuno** [hrt4423/Asoda#87]
ボタンを押したときｃｓｓでclickedで色を変える様にしているが、先頭の１個しかボタンの色が変わらず、このままbuttonのままで解決できるのか、それともチェックボックスでやったほうがいいのか？
ｈｔｍｌ
<button id="myBtn">131</button>
ｃｓｓ
#myBtn {
  background-color: lawngreen;
  color: black;
}

#myBtn.clicked {
  background-color: grey;
}

**Comment by hrt4423** [comment]
チェックボックスを使う方法だと出来ました。以下のサイトの "**クリックしたら色が変わる（複数選択可**）"を参考にしてみてください。
https://csshtml.work/click-button/

**Comment by kazubetsuno** [comment]
確認しました
